### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by michabbb** [laravel-workflow/waterline#2]
https://github.com/laravel-workflow/waterline/blob/a84e67f4e06a455d976bf3150509a29006ae83fe/composer.json#L13

```txt
laravel-workflow/waterline 0.0.5 requires laravel-workflow/laravel-workflow ^0.0.11 -> found laravel-workflow/laravel-workflow[0.0.11] but it conflicts with your root composer.json require (^0.0.13).
```

**Comment by rmcdaniel** [comment]
Fixed in waterline version 0.0.6! You should be able to just run the composer require command again and it'll work now.
