### ISSUE TITLE
Ukrainian anthem in app.js 

### ISSUE THREAD

**Issue by nqxcode** [laravel-workflow/waterline#28]
Authors, remove "policy" from the package. File https://github.com/laravel-workflow/waterline/blob/master/public/app.js

**Comment by nqxcode** [comment]
![изображение](https://github.com/laravel-workflow/waterline/assets/5667387/d4048a91-866d-451d-b51a-096306c930f2)

**Comment by rmcdaniel** [comment]
https://github.com/sweetalert2/sweetalert2/issues/2552

I apologize for that. It was apparently added by a very misguided developer. This is not appropriate. I will look for a solution. If you have one please submit a PR.

**Comment by rmcdaniel** [comment]
It looks like one option would be to lock it to a previous version that doesn't contain the malware.

**Comment by rmcdaniel** [comment]
https://github.com/lofcz/sweetalert2-neutral/ is another option.

**Comment by nqxcode** [comment]
ok, PR https://github.com/laravel-workflow/waterline/pull/29

**Comment by rmcdaniel** [comment]
@nqxcode Can you take a look at https://github.com/laravel-workflow/waterline/pull/30 which is a more permanent fix?
