### ISSUE TITLE
Change the DB connection on StoredWorkflow?

### ISSUE THREAD

**Issue by dragonfire1119** [laravel-workflow/waterline#5]
If you alter the DB connection on Workflow or Activities, there doesn't appear to be a way to update the DB connection of the StoredWorkflow.

**Comment by rmcdaniel** [comment]
Do you mean like this? https://laravel.com/docs/9.x/eloquent#database-connections

If that's what you mean then I think I will have to create a publishable configuration file for LW that allows you to specify your own custom StoredWorkflow model that extends the one that this package provides.

**Comment by dragonfire1119** [comment]
> Do you mean like this? https://laravel.com/docs/9.x/eloquent#database-connections
> 
> If that's what you mean then I think I will have to create a publishable configuration file for LW that allows you to specify your own custom StoredWorkflow model that extends the one that this package provides.

That's exactly what I mean. Thank you for responding.

I was considering putting the Workflow schema in its own database so that I could share functionality throughout all of the services. I was looking for a config but didn't see one that's why I started the issue.

**Comment by rmcdaniel** [comment]
Understood. I'll get this done in the next release very soon!

**Comment by rmcdaniel** [comment]
@dragonfire1119 https://github.com/laravel-workflow/laravel-workflow/wiki/6.-Workflow-and-Activity-Options#custom-database-connection It's in the latest release!

**Comment by rmcdaniel** [comment]
I just realized I forgot to publish the waterline release. Please stand by.

**Comment by rmcdaniel** [comment]
Done!

**Comment by dragonfire1119** [comment]
Wow, that was quick! Thanks, man!
